# Generated by Django 5.2 on 2025-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cartitem_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No subject', max_length=200),
            preserve_default=False,
        ),
    ]
