# Generated by Django 5.2 on 2025-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('specialization', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=15)),
            ],
        ),
    ]
